version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=http://backend:3001
    ports:
      - "9999:3000"
    volumes:
      - ./frontend:/app
      - /frontend/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    environment:
#      - BACKEND_URL=http://backend:3001
      - TEST_ENV=Test
    # the build args are defined by this key


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CONNECTION_STRING=mongodb+srv://tongducthanhnam:p4KZY1s74HJPqWfb@ecomerce.ocviy.mongodb.net/?retryWrites=true&w=majority&appName=Ecomerce
      - DATABASE_NAME=e-commerce
    volumes:
      - ./backend:/app
      - /backend/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge