version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=${BACKEND_URL}
        - NEXT_PUBLIC_DOMAIN=${NEXT_PUBLIC_DOMAIN}
      target: release
    image:
      tongducthanhnam/nextui-ecommerce-fe:latest
    volumes:
      - ./frontend:/app
    ports:
      - "9999:3000"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - BACKEND_URL=${BACKEND_URL}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
        - PORT=${PORT}
        - CONNECTION_STRING=${CONNECTION_STRING}
        - DATABASE_NAME=${DATABASE_NAME}
        - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
        - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
        - NOTION_API_KEY=${NOTION_API_KEY}
        - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      target: release
    image:
      tongducthanhnam/nextui-ecommerce-be:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - CONNECTION_STRING=${CONNECTION_STRING}
      - DATABASE_NAME=${DATABASE_NAME}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
    networks:
      - app-network
    volumes:
      - ./backend:/app

networks:
  app-network:
    driver: bridge