/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SanPhamRouteImport } from './routes/san-pham'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as QuenMatKhauRouteImport } from './routes/quen-mat-khau'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as GioHangRouteImport } from './routes/gio-hang'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DanhSachSanPhamRouteImport } from './routes/danh-sach-san-pham'
import { Route as DangNhapRouteImport } from './routes/dang-nhap'
import { Route as DangKyRouteImport } from './routes/dang-ky'
import { Route as BaiVietRouteImport } from './routes/bai-viet'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as AddProductRouteImport } from './routes/add-product'
import { Route as AddOrderRouteImport } from './routes/add-order'
import { Route as AddInventoryRouteImport } from './routes/add-inventory'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ViewProductProductIdRouteImport } from './routes/view-product/$productId'
import { Route as SanPhamProductIdRouteImport } from './routes/san-pham/$productId'
import { Route as EditProductProductIdRouteImport } from './routes/edit-product/$productId'
import { Route as BaiVietSlugRouteImport } from './routes/bai-viet/$slug'
import { Route as ApiSendProductOrderRouteImport } from './routes/api/send-product-order'
import { Route as ApiSendNewsletterRouteImport } from './routes/api/send-newsletter'
import { Route as ApiSendNewletterRouteImport } from './routes/api/send-newletter'
import { Route as ApiSendCartOrderRouteImport } from './routes/api/send-cart-order'
import { Route as ApiProductsRouteImport } from './routes/api/products'
import { Route as ApiProductRouteImport } from './routes/api/product'
import { Route as ApiPostsRouteImport } from './routes/api/posts'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as ApiLogsRouteImport } from './routes/api/logs'
import { Route as ApiGetBookmarkRouteImport } from './routes/api/get-bookmark'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as ApiAddProductRouteImport } from './routes/api/add-product'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAddProductRouteImport } from './routes/admin/add-product'
import { Route as ApiUploadsProductImagesRouteImport } from './routes/api/uploads/product-images'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiProductsProductIdRouteImport } from './routes/api/products/$productId'
import { Route as ApiProductProductIdRouteImport } from './routes/api/product/$productId'
import { Route as ApiProductImagesKeyRouteImport } from './routes/api/product-images/$key'
import { Route as ApiPostsSlugRouteImport } from './routes/api/posts/$slug'
import { Route as ApiOrdersOrderIdRouteImport } from './routes/api/orders/$orderId'
import { Route as ApiLogsLogIdRouteImport } from './routes/api/logs/$logId'
import { Route as ApiEditProductProductIdRouteImport } from './routes/api/edit-product/$productId'
import { Route as ApiCategoriesCategoryIdRouteImport } from './routes/api/categories/$categoryId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminViewProductProductIdRouteImport } from './routes/admin/view-product/$productId'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminProductsProductIdRouteImport } from './routes/admin/products/$productId'
import { Route as AdminOrdersNewRouteImport } from './routes/admin/orders/new'
import { Route as AdminInventoryNewRouteImport } from './routes/admin/inventory/new'
import { Route as AdminEditProductProductIdRouteImport } from './routes/admin/edit-product/$productId'
import { Route as ApiProductProductIdVariantRouteImport } from './routes/api/product/$productId/variant'
import { Route as AdminProductsProductIdEditRouteImport } from './routes/admin/products/$productId/edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamRoute = SanPhamRouteImport.update({
  id: '/san-pham',
  path: '/san-pham',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const QuenMatKhauRoute = QuenMatKhauRouteImport.update({
  id: '/quen-mat-khau',
  path: '/quen-mat-khau',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const GioHangRoute = GioHangRouteImport.update({
  id: '/gio-hang',
  path: '/gio-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DanhSachSanPhamRoute = DanhSachSanPhamRouteImport.update({
  id: '/danh-sach-san-pham',
  path: '/danh-sach-san-pham',
  getParentRoute: () => rootRouteImport,
} as any)
const DangNhapRoute = DangNhapRouteImport.update({
  id: '/dang-nhap',
  path: '/dang-nhap',
  getParentRoute: () => rootRouteImport,
} as any)
const DangKyRoute = DangKyRouteImport.update({
  id: '/dang-ky',
  path: '/dang-ky',
  getParentRoute: () => rootRouteImport,
} as any)
const BaiVietRoute = BaiVietRouteImport.update({
  id: '/bai-viet',
  path: '/bai-viet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AddProductRoute = AddProductRouteImport.update({
  id: '/add-product',
  path: '/add-product',
  getParentRoute: () => rootRouteImport,
} as any)
const AddOrderRoute = AddOrderRouteImport.update({
  id: '/add-order',
  path: '/add-order',
  getParentRoute: () => rootRouteImport,
} as any)
const AddInventoryRoute = AddInventoryRouteImport.update({
  id: '/add-inventory',
  path: '/add-inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewProductProductIdRoute = ViewProductProductIdRouteImport.update({
  id: '/view-product/$productId',
  path: '/view-product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamProductIdRoute = SanPhamProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => SanPhamRoute,
} as any)
const EditProductProductIdRoute = EditProductProductIdRouteImport.update({
  id: '/edit-product/$productId',
  path: '/edit-product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const BaiVietSlugRoute = BaiVietSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BaiVietRoute,
} as any)
const ApiSendProductOrderRoute = ApiSendProductOrderRouteImport.update({
  id: '/api/send-product-order',
  path: '/api/send-product-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendNewsletterRoute = ApiSendNewsletterRouteImport.update({
  id: '/api/send-newsletter',
  path: '/api/send-newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendNewletterRoute = ApiSendNewletterRouteImport.update({
  id: '/api/send-newletter',
  path: '/api/send-newletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendCartOrderRoute = ApiSendCartOrderRouteImport.update({
  id: '/api/send-cart-order',
  path: '/api/send-cart-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductRoute = ApiProductRouteImport.update({
  id: '/api/product',
  path: '/api/product',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsRoute = ApiPostsRouteImport.update({
  id: '/api/posts',
  path: '/api/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogsRoute = ApiLogsRouteImport.update({
  id: '/api/logs',
  path: '/api/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGetBookmarkRoute = ApiGetBookmarkRouteImport.update({
  id: '/api/get-bookmark',
  path: '/api/get-bookmark',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAddProductRoute = ApiAddProductRouteImport.update({
  id: '/api/add-product',
  path: '/api/add-product',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAddProductRoute = AdminAddProductRouteImport.update({
  id: '/admin/add-product',
  path: '/admin/add-product',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsProductImagesRoute = ApiUploadsProductImagesRouteImport.update({
  id: '/api/uploads/product-images',
  path: '/api/uploads/product-images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsProductIdRoute = ApiProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ApiProductsRoute,
} as any)
const ApiProductProductIdRoute = ApiProductProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ApiProductRoute,
} as any)
const ApiProductImagesKeyRoute = ApiProductImagesKeyRouteImport.update({
  id: '/api/product-images/$key',
  path: '/api/product-images/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsSlugRoute = ApiPostsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiPostsRoute,
} as any)
const ApiOrdersOrderIdRoute = ApiOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => ApiOrdersRoute,
} as any)
const ApiLogsLogIdRoute = ApiLogsLogIdRouteImport.update({
  id: '/$logId',
  path: '/$logId',
  getParentRoute: () => ApiLogsRoute,
} as any)
const ApiEditProductProductIdRoute = ApiEditProductProductIdRouteImport.update({
  id: '/api/edit-product/$productId',
  path: '/api/edit-product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesCategoryIdRoute = ApiCategoriesCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => ApiCategoriesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminViewProductProductIdRoute =
  AdminViewProductProductIdRouteImport.update({
    id: '/admin/view-product/$productId',
    path: '/admin/view-product/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsProductIdRoute = AdminProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminOrdersNewRoute = AdminOrdersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminInventoryNewRoute = AdminInventoryNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminInventoryRoute,
} as any)
const AdminEditProductProductIdRoute =
  AdminEditProductProductIdRouteImport.update({
    id: '/admin/edit-product/$productId',
    path: '/admin/edit-product/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProductProductIdVariantRoute =
  ApiProductProductIdVariantRouteImport.update({
    id: '/variant',
    path: '/variant',
    getParentRoute: () => ApiProductProductIdRoute,
  } as any)
const AdminProductsProductIdEditRoute =
  AdminProductsProductIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminProductsProductIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-inventory': typeof AddInventoryRoute
  '/add-order': typeof AddOrderRoute
  '/add-product': typeof AddProductRoute
  '/api-docs': typeof ApiDocsRoute
  '/bai-viet': typeof BaiVietRouteWithChildren
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/danh-sach-san-pham': typeof DanhSachSanPhamRoute
  '/dashboard': typeof DashboardRoute
  '/gio-hang': typeof GioHangRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/not-found': typeof NotFoundRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/quen-mat-khau': typeof QuenMatKhauRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/san-pham': typeof SanPhamRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/add-product': typeof AdminAddProductRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inventory': typeof AdminInventoryRouteWithChildren
  '/admin/logs': typeof AdminLogsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/api/add-product': typeof ApiAddProductRoute
  '/api/categories': typeof ApiCategoriesRouteWithChildren
  '/api/get-bookmark': typeof ApiGetBookmarkRoute
  '/api/logs': typeof ApiLogsRouteWithChildren
  '/api/orders': typeof ApiOrdersRouteWithChildren
  '/api/posts': typeof ApiPostsRouteWithChildren
  '/api/product': typeof ApiProductRouteWithChildren
  '/api/products': typeof ApiProductsRouteWithChildren
  '/api/send-cart-order': typeof ApiSendCartOrderRoute
  '/api/send-newletter': typeof ApiSendNewletterRoute
  '/api/send-newsletter': typeof ApiSendNewsletterRoute
  '/api/send-product-order': typeof ApiSendProductOrderRoute
  '/bai-viet/$slug': typeof BaiVietSlugRoute
  '/edit-product/$productId': typeof EditProductProductIdRoute
  '/san-pham/$productId': typeof SanPhamProductIdRoute
  '/view-product/$productId': typeof ViewProductProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/edit-product/$productId': typeof AdminEditProductProductIdRoute
  '/admin/inventory/new': typeof AdminInventoryNewRoute
  '/admin/orders/new': typeof AdminOrdersNewRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRouteWithChildren
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/view-product/$productId': typeof AdminViewProductProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/categories/$categoryId': typeof ApiCategoriesCategoryIdRoute
  '/api/edit-product/$productId': typeof ApiEditProductProductIdRoute
  '/api/logs/$logId': typeof ApiLogsLogIdRoute
  '/api/orders/$orderId': typeof ApiOrdersOrderIdRoute
  '/api/posts/$slug': typeof ApiPostsSlugRoute
  '/api/product-images/$key': typeof ApiProductImagesKeyRoute
  '/api/product/$productId': typeof ApiProductProductIdRouteWithChildren
  '/api/products/$productId': typeof ApiProductsProductIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/uploads/product-images': typeof ApiUploadsProductImagesRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
  '/api/product/$productId/variant': typeof ApiProductProductIdVariantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-inventory': typeof AddInventoryRoute
  '/add-order': typeof AddOrderRoute
  '/add-product': typeof AddProductRoute
  '/api-docs': typeof ApiDocsRoute
  '/bai-viet': typeof BaiVietRouteWithChildren
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/danh-sach-san-pham': typeof DanhSachSanPhamRoute
  '/dashboard': typeof DashboardRoute
  '/gio-hang': typeof GioHangRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/not-found': typeof NotFoundRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/quen-mat-khau': typeof QuenMatKhauRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/san-pham': typeof SanPhamRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/add-product': typeof AdminAddProductRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inventory': typeof AdminInventoryRouteWithChildren
  '/admin/logs': typeof AdminLogsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/api/add-product': typeof ApiAddProductRoute
  '/api/categories': typeof ApiCategoriesRouteWithChildren
  '/api/get-bookmark': typeof ApiGetBookmarkRoute
  '/api/logs': typeof ApiLogsRouteWithChildren
  '/api/orders': typeof ApiOrdersRouteWithChildren
  '/api/posts': typeof ApiPostsRouteWithChildren
  '/api/product': typeof ApiProductRouteWithChildren
  '/api/products': typeof ApiProductsRouteWithChildren
  '/api/send-cart-order': typeof ApiSendCartOrderRoute
  '/api/send-newletter': typeof ApiSendNewletterRoute
  '/api/send-newsletter': typeof ApiSendNewsletterRoute
  '/api/send-product-order': typeof ApiSendProductOrderRoute
  '/bai-viet/$slug': typeof BaiVietSlugRoute
  '/edit-product/$productId': typeof EditProductProductIdRoute
  '/san-pham/$productId': typeof SanPhamProductIdRoute
  '/view-product/$productId': typeof ViewProductProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/edit-product/$productId': typeof AdminEditProductProductIdRoute
  '/admin/inventory/new': typeof AdminInventoryNewRoute
  '/admin/orders/new': typeof AdminOrdersNewRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRouteWithChildren
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/view-product/$productId': typeof AdminViewProductProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/categories/$categoryId': typeof ApiCategoriesCategoryIdRoute
  '/api/edit-product/$productId': typeof ApiEditProductProductIdRoute
  '/api/logs/$logId': typeof ApiLogsLogIdRoute
  '/api/orders/$orderId': typeof ApiOrdersOrderIdRoute
  '/api/posts/$slug': typeof ApiPostsSlugRoute
  '/api/product-images/$key': typeof ApiProductImagesKeyRoute
  '/api/product/$productId': typeof ApiProductProductIdRouteWithChildren
  '/api/products/$productId': typeof ApiProductsProductIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/uploads/product-images': typeof ApiUploadsProductImagesRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
  '/api/product/$productId/variant': typeof ApiProductProductIdVariantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-inventory': typeof AddInventoryRoute
  '/add-order': typeof AddOrderRoute
  '/add-product': typeof AddProductRoute
  '/api-docs': typeof ApiDocsRoute
  '/bai-viet': typeof BaiVietRouteWithChildren
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/danh-sach-san-pham': typeof DanhSachSanPhamRoute
  '/dashboard': typeof DashboardRoute
  '/gio-hang': typeof GioHangRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/not-found': typeof NotFoundRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/quen-mat-khau': typeof QuenMatKhauRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/san-pham': typeof SanPhamRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/add-product': typeof AdminAddProductRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inventory': typeof AdminInventoryRouteWithChildren
  '/admin/logs': typeof AdminLogsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/api/add-product': typeof ApiAddProductRoute
  '/api/categories': typeof ApiCategoriesRouteWithChildren
  '/api/get-bookmark': typeof ApiGetBookmarkRoute
  '/api/logs': typeof ApiLogsRouteWithChildren
  '/api/orders': typeof ApiOrdersRouteWithChildren
  '/api/posts': typeof ApiPostsRouteWithChildren
  '/api/product': typeof ApiProductRouteWithChildren
  '/api/products': typeof ApiProductsRouteWithChildren
  '/api/send-cart-order': typeof ApiSendCartOrderRoute
  '/api/send-newletter': typeof ApiSendNewletterRoute
  '/api/send-newsletter': typeof ApiSendNewsletterRoute
  '/api/send-product-order': typeof ApiSendProductOrderRoute
  '/bai-viet/$slug': typeof BaiVietSlugRoute
  '/edit-product/$productId': typeof EditProductProductIdRoute
  '/san-pham/$productId': typeof SanPhamProductIdRoute
  '/view-product/$productId': typeof ViewProductProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/edit-product/$productId': typeof AdminEditProductProductIdRoute
  '/admin/inventory/new': typeof AdminInventoryNewRoute
  '/admin/orders/new': typeof AdminOrdersNewRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRouteWithChildren
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/view-product/$productId': typeof AdminViewProductProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/categories/$categoryId': typeof ApiCategoriesCategoryIdRoute
  '/api/edit-product/$productId': typeof ApiEditProductProductIdRoute
  '/api/logs/$logId': typeof ApiLogsLogIdRoute
  '/api/orders/$orderId': typeof ApiOrdersOrderIdRoute
  '/api/posts/$slug': typeof ApiPostsSlugRoute
  '/api/product-images/$key': typeof ApiProductImagesKeyRoute
  '/api/product/$productId': typeof ApiProductProductIdRouteWithChildren
  '/api/products/$productId': typeof ApiProductsProductIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/uploads/product-images': typeof ApiUploadsProductImagesRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
  '/api/product/$productId/variant': typeof ApiProductProductIdVariantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-inventory'
    | '/add-order'
    | '/add-product'
    | '/api-docs'
    | '/bai-viet'
    | '/dang-ky'
    | '/dang-nhap'
    | '/danh-sach-san-pham'
    | '/dashboard'
    | '/gio-hang'
    | '/gioi-thieu'
    | '/inventory'
    | '/login'
    | '/manifest.webmanifest'
    | '/not-found'
    | '/orders'
    | '/products'
    | '/quen-mat-khau'
    | '/robots.txt'
    | '/san-pham'
    | '/sitemap.xml'
    | '/admin/add-product'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/logs'
    | '/admin/orders'
    | '/admin/products'
    | '/api/add-product'
    | '/api/categories'
    | '/api/get-bookmark'
    | '/api/logs'
    | '/api/orders'
    | '/api/posts'
    | '/api/product'
    | '/api/products'
    | '/api/send-cart-order'
    | '/api/send-newletter'
    | '/api/send-newsletter'
    | '/api/send-product-order'
    | '/bai-viet/$slug'
    | '/edit-product/$productId'
    | '/san-pham/$productId'
    | '/view-product/$productId'
    | '/admin/'
    | '/admin/edit-product/$productId'
    | '/admin/inventory/new'
    | '/admin/orders/new'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/view-product/$productId'
    | '/api/auth/$'
    | '/api/categories/$categoryId'
    | '/api/edit-product/$productId'
    | '/api/logs/$logId'
    | '/api/orders/$orderId'
    | '/api/posts/$slug'
    | '/api/product-images/$key'
    | '/api/product/$productId'
    | '/api/products/$productId'
    | '/api/trpc/$'
    | '/api/uploads/product-images'
    | '/admin/products/$productId/edit'
    | '/api/product/$productId/variant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-inventory'
    | '/add-order'
    | '/add-product'
    | '/api-docs'
    | '/bai-viet'
    | '/dang-ky'
    | '/dang-nhap'
    | '/danh-sach-san-pham'
    | '/dashboard'
    | '/gio-hang'
    | '/gioi-thieu'
    | '/inventory'
    | '/login'
    | '/manifest.webmanifest'
    | '/not-found'
    | '/orders'
    | '/products'
    | '/quen-mat-khau'
    | '/robots.txt'
    | '/san-pham'
    | '/sitemap.xml'
    | '/admin/add-product'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/logs'
    | '/admin/orders'
    | '/admin/products'
    | '/api/add-product'
    | '/api/categories'
    | '/api/get-bookmark'
    | '/api/logs'
    | '/api/orders'
    | '/api/posts'
    | '/api/product'
    | '/api/products'
    | '/api/send-cart-order'
    | '/api/send-newletter'
    | '/api/send-newsletter'
    | '/api/send-product-order'
    | '/bai-viet/$slug'
    | '/edit-product/$productId'
    | '/san-pham/$productId'
    | '/view-product/$productId'
    | '/admin'
    | '/admin/edit-product/$productId'
    | '/admin/inventory/new'
    | '/admin/orders/new'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/view-product/$productId'
    | '/api/auth/$'
    | '/api/categories/$categoryId'
    | '/api/edit-product/$productId'
    | '/api/logs/$logId'
    | '/api/orders/$orderId'
    | '/api/posts/$slug'
    | '/api/product-images/$key'
    | '/api/product/$productId'
    | '/api/products/$productId'
    | '/api/trpc/$'
    | '/api/uploads/product-images'
    | '/admin/products/$productId/edit'
    | '/api/product/$productId/variant'
  id:
    | '__root__'
    | '/'
    | '/add-inventory'
    | '/add-order'
    | '/add-product'
    | '/api-docs'
    | '/bai-viet'
    | '/dang-ky'
    | '/dang-nhap'
    | '/danh-sach-san-pham'
    | '/dashboard'
    | '/gio-hang'
    | '/gioi-thieu'
    | '/inventory'
    | '/login'
    | '/manifest.webmanifest'
    | '/not-found'
    | '/orders'
    | '/products'
    | '/quen-mat-khau'
    | '/robots.txt'
    | '/san-pham'
    | '/sitemap.xml'
    | '/admin/add-product'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/logs'
    | '/admin/orders'
    | '/admin/products'
    | '/api/add-product'
    | '/api/categories'
    | '/api/get-bookmark'
    | '/api/logs'
    | '/api/orders'
    | '/api/posts'
    | '/api/product'
    | '/api/products'
    | '/api/send-cart-order'
    | '/api/send-newletter'
    | '/api/send-newsletter'
    | '/api/send-product-order'
    | '/bai-viet/$slug'
    | '/edit-product/$productId'
    | '/san-pham/$productId'
    | '/view-product/$productId'
    | '/admin/'
    | '/admin/edit-product/$productId'
    | '/admin/inventory/new'
    | '/admin/orders/new'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/view-product/$productId'
    | '/api/auth/$'
    | '/api/categories/$categoryId'
    | '/api/edit-product/$productId'
    | '/api/logs/$logId'
    | '/api/orders/$orderId'
    | '/api/posts/$slug'
    | '/api/product-images/$key'
    | '/api/product/$productId'
    | '/api/products/$productId'
    | '/api/trpc/$'
    | '/api/uploads/product-images'
    | '/admin/products/$productId/edit'
    | '/api/product/$productId/variant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddInventoryRoute: typeof AddInventoryRoute
  AddOrderRoute: typeof AddOrderRoute
  AddProductRoute: typeof AddProductRoute
  ApiDocsRoute: typeof ApiDocsRoute
  BaiVietRoute: typeof BaiVietRouteWithChildren
  DangKyRoute: typeof DangKyRoute
  DangNhapRoute: typeof DangNhapRoute
  DanhSachSanPhamRoute: typeof DanhSachSanPhamRoute
  DashboardRoute: typeof DashboardRoute
  GioHangRoute: typeof GioHangRoute
  GioiThieuRoute: typeof GioiThieuRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  NotFoundRoute: typeof NotFoundRoute
  OrdersRoute: typeof OrdersRoute
  ProductsRoute: typeof ProductsRoute
  QuenMatKhauRoute: typeof QuenMatKhauRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SanPhamRoute: typeof SanPhamRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminAddProductRoute: typeof AdminAddProductRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminInventoryRoute: typeof AdminInventoryRouteWithChildren
  AdminLogsRoute: typeof AdminLogsRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  ApiAddProductRoute: typeof ApiAddProductRoute
  ApiCategoriesRoute: typeof ApiCategoriesRouteWithChildren
  ApiGetBookmarkRoute: typeof ApiGetBookmarkRoute
  ApiLogsRoute: typeof ApiLogsRouteWithChildren
  ApiOrdersRoute: typeof ApiOrdersRouteWithChildren
  ApiPostsRoute: typeof ApiPostsRouteWithChildren
  ApiProductRoute: typeof ApiProductRouteWithChildren
  ApiProductsRoute: typeof ApiProductsRouteWithChildren
  ApiSendCartOrderRoute: typeof ApiSendCartOrderRoute
  ApiSendNewletterRoute: typeof ApiSendNewletterRoute
  ApiSendNewsletterRoute: typeof ApiSendNewsletterRoute
  ApiSendProductOrderRoute: typeof ApiSendProductOrderRoute
  EditProductProductIdRoute: typeof EditProductProductIdRoute
  ViewProductProductIdRoute: typeof ViewProductProductIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEditProductProductIdRoute: typeof AdminEditProductProductIdRoute
  AdminViewProductProductIdRoute: typeof AdminViewProductProductIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiEditProductProductIdRoute: typeof ApiEditProductProductIdRoute
  ApiProductImagesKeyRoute: typeof ApiProductImagesKeyRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiUploadsProductImagesRoute: typeof ApiUploadsProductImagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham': {
      id: '/san-pham'
      path: '/san-pham'
      fullPath: '/san-pham'
      preLoaderRoute: typeof SanPhamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quen-mat-khau': {
      id: '/quen-mat-khau'
      path: '/quen-mat-khau'
      fullPath: '/quen-mat-khau'
      preLoaderRoute: typeof QuenMatKhauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gio-hang': {
      id: '/gio-hang'
      path: '/gio-hang'
      fullPath: '/gio-hang'
      preLoaderRoute: typeof GioHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/danh-sach-san-pham': {
      id: '/danh-sach-san-pham'
      path: '/danh-sach-san-pham'
      fullPath: '/danh-sach-san-pham'
      preLoaderRoute: typeof DanhSachSanPhamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-nhap': {
      id: '/dang-nhap'
      path: '/dang-nhap'
      fullPath: '/dang-nhap'
      preLoaderRoute: typeof DangNhapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-ky': {
      id: '/dang-ky'
      path: '/dang-ky'
      fullPath: '/dang-ky'
      preLoaderRoute: typeof DangKyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bai-viet': {
      id: '/bai-viet'
      path: '/bai-viet'
      fullPath: '/bai-viet'
      preLoaderRoute: typeof BaiVietRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-product': {
      id: '/add-product'
      path: '/add-product'
      fullPath: '/add-product'
      preLoaderRoute: typeof AddProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-order': {
      id: '/add-order'
      path: '/add-order'
      fullPath: '/add-order'
      preLoaderRoute: typeof AddOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-inventory': {
      id: '/add-inventory'
      path: '/add-inventory'
      fullPath: '/add-inventory'
      preLoaderRoute: typeof AddInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view-product/$productId': {
      id: '/view-product/$productId'
      path: '/view-product/$productId'
      fullPath: '/view-product/$productId'
      preLoaderRoute: typeof ViewProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham/$productId': {
      id: '/san-pham/$productId'
      path: '/$productId'
      fullPath: '/san-pham/$productId'
      preLoaderRoute: typeof SanPhamProductIdRouteImport
      parentRoute: typeof SanPhamRoute
    }
    '/edit-product/$productId': {
      id: '/edit-product/$productId'
      path: '/edit-product/$productId'
      fullPath: '/edit-product/$productId'
      preLoaderRoute: typeof EditProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bai-viet/$slug': {
      id: '/bai-viet/$slug'
      path: '/$slug'
      fullPath: '/bai-viet/$slug'
      preLoaderRoute: typeof BaiVietSlugRouteImport
      parentRoute: typeof BaiVietRoute
    }
    '/api/send-product-order': {
      id: '/api/send-product-order'
      path: '/api/send-product-order'
      fullPath: '/api/send-product-order'
      preLoaderRoute: typeof ApiSendProductOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-newsletter': {
      id: '/api/send-newsletter'
      path: '/api/send-newsletter'
      fullPath: '/api/send-newsletter'
      preLoaderRoute: typeof ApiSendNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-newletter': {
      id: '/api/send-newletter'
      path: '/api/send-newletter'
      fullPath: '/api/send-newletter'
      preLoaderRoute: typeof ApiSendNewletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-cart-order': {
      id: '/api/send-cart-order'
      path: '/api/send-cart-order'
      fullPath: '/api/send-cart-order'
      preLoaderRoute: typeof ApiSendCartOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/product': {
      id: '/api/product'
      path: '/api/product'
      fullPath: '/api/product'
      preLoaderRoute: typeof ApiProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts': {
      id: '/api/posts'
      path: '/api/posts'
      fullPath: '/api/posts'
      preLoaderRoute: typeof ApiPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logs': {
      id: '/api/logs'
      path: '/api/logs'
      fullPath: '/api/logs'
      preLoaderRoute: typeof ApiLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/get-bookmark': {
      id: '/api/get-bookmark'
      path: '/api/get-bookmark'
      fullPath: '/api/get-bookmark'
      preLoaderRoute: typeof ApiGetBookmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/add-product': {
      id: '/api/add-product'
      path: '/api/add-product'
      fullPath: '/api/add-product'
      preLoaderRoute: typeof ApiAddProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/add-product': {
      id: '/admin/add-product'
      path: '/admin/add-product'
      fullPath: '/admin/add-product'
      preLoaderRoute: typeof AdminAddProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/product-images': {
      id: '/api/uploads/product-images'
      path: '/api/uploads/product-images'
      fullPath: '/api/uploads/product-images'
      preLoaderRoute: typeof ApiUploadsProductImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/$productId': {
      id: '/api/products/$productId'
      path: '/$productId'
      fullPath: '/api/products/$productId'
      preLoaderRoute: typeof ApiProductsProductIdRouteImport
      parentRoute: typeof ApiProductsRoute
    }
    '/api/product/$productId': {
      id: '/api/product/$productId'
      path: '/$productId'
      fullPath: '/api/product/$productId'
      preLoaderRoute: typeof ApiProductProductIdRouteImport
      parentRoute: typeof ApiProductRoute
    }
    '/api/product-images/$key': {
      id: '/api/product-images/$key'
      path: '/api/product-images/$key'
      fullPath: '/api/product-images/$key'
      preLoaderRoute: typeof ApiProductImagesKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/$slug': {
      id: '/api/posts/$slug'
      path: '/$slug'
      fullPath: '/api/posts/$slug'
      preLoaderRoute: typeof ApiPostsSlugRouteImport
      parentRoute: typeof ApiPostsRoute
    }
    '/api/orders/$orderId': {
      id: '/api/orders/$orderId'
      path: '/$orderId'
      fullPath: '/api/orders/$orderId'
      preLoaderRoute: typeof ApiOrdersOrderIdRouteImport
      parentRoute: typeof ApiOrdersRoute
    }
    '/api/logs/$logId': {
      id: '/api/logs/$logId'
      path: '/$logId'
      fullPath: '/api/logs/$logId'
      preLoaderRoute: typeof ApiLogsLogIdRouteImport
      parentRoute: typeof ApiLogsRoute
    }
    '/api/edit-product/$productId': {
      id: '/api/edit-product/$productId'
      path: '/api/edit-product/$productId'
      fullPath: '/api/edit-product/$productId'
      preLoaderRoute: typeof ApiEditProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories/$categoryId': {
      id: '/api/categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/api/categories/$categoryId'
      preLoaderRoute: typeof ApiCategoriesCategoryIdRouteImport
      parentRoute: typeof ApiCategoriesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/view-product/$productId': {
      id: '/admin/view-product/$productId'
      path: '/admin/view-product/$productId'
      fullPath: '/admin/view-product/$productId'
      preLoaderRoute: typeof AdminViewProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/$productId': {
      id: '/admin/products/$productId'
      path: '/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AdminProductsProductIdRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/orders/new': {
      id: '/admin/orders/new'
      path: '/new'
      fullPath: '/admin/orders/new'
      preLoaderRoute: typeof AdminOrdersNewRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/inventory/new': {
      id: '/admin/inventory/new'
      path: '/new'
      fullPath: '/admin/inventory/new'
      preLoaderRoute: typeof AdminInventoryNewRouteImport
      parentRoute: typeof AdminInventoryRoute
    }
    '/admin/edit-product/$productId': {
      id: '/admin/edit-product/$productId'
      path: '/admin/edit-product/$productId'
      fullPath: '/admin/edit-product/$productId'
      preLoaderRoute: typeof AdminEditProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/product/$productId/variant': {
      id: '/api/product/$productId/variant'
      path: '/variant'
      fullPath: '/api/product/$productId/variant'
      preLoaderRoute: typeof ApiProductProductIdVariantRouteImport
      parentRoute: typeof ApiProductProductIdRoute
    }
    '/admin/products/$productId/edit': {
      id: '/admin/products/$productId/edit'
      path: '/edit'
      fullPath: '/admin/products/$productId/edit'
      preLoaderRoute: typeof AdminProductsProductIdEditRouteImport
      parentRoute: typeof AdminProductsProductIdRoute
    }
  }
}

interface BaiVietRouteChildren {
  BaiVietSlugRoute: typeof BaiVietSlugRoute
}

const BaiVietRouteChildren: BaiVietRouteChildren = {
  BaiVietSlugRoute: BaiVietSlugRoute,
}

const BaiVietRouteWithChildren =
  BaiVietRoute._addFileChildren(BaiVietRouteChildren)

interface SanPhamRouteChildren {
  SanPhamProductIdRoute: typeof SanPhamProductIdRoute
}

const SanPhamRouteChildren: SanPhamRouteChildren = {
  SanPhamProductIdRoute: SanPhamProductIdRoute,
}

const SanPhamRouteWithChildren =
  SanPhamRoute._addFileChildren(SanPhamRouteChildren)

interface AdminInventoryRouteChildren {
  AdminInventoryNewRoute: typeof AdminInventoryNewRoute
}

const AdminInventoryRouteChildren: AdminInventoryRouteChildren = {
  AdminInventoryNewRoute: AdminInventoryNewRoute,
}

const AdminInventoryRouteWithChildren = AdminInventoryRoute._addFileChildren(
  AdminInventoryRouteChildren,
)

interface AdminOrdersRouteChildren {
  AdminOrdersNewRoute: typeof AdminOrdersNewRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersNewRoute: AdminOrdersNewRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminProductsProductIdRouteChildren {
  AdminProductsProductIdEditRoute: typeof AdminProductsProductIdEditRoute
}

const AdminProductsProductIdRouteChildren: AdminProductsProductIdRouteChildren =
  {
    AdminProductsProductIdEditRoute: AdminProductsProductIdEditRoute,
  }

const AdminProductsProductIdRouteWithChildren =
  AdminProductsProductIdRoute._addFileChildren(
    AdminProductsProductIdRouteChildren,
  )

interface AdminProductsRouteChildren {
  AdminProductsProductIdRoute: typeof AdminProductsProductIdRouteWithChildren
  AdminProductsNewRoute: typeof AdminProductsNewRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsProductIdRoute: AdminProductsProductIdRouteWithChildren,
  AdminProductsNewRoute: AdminProductsNewRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface ApiCategoriesRouteChildren {
  ApiCategoriesCategoryIdRoute: typeof ApiCategoriesCategoryIdRoute
}

const ApiCategoriesRouteChildren: ApiCategoriesRouteChildren = {
  ApiCategoriesCategoryIdRoute: ApiCategoriesCategoryIdRoute,
}

const ApiCategoriesRouteWithChildren = ApiCategoriesRoute._addFileChildren(
  ApiCategoriesRouteChildren,
)

interface ApiLogsRouteChildren {
  ApiLogsLogIdRoute: typeof ApiLogsLogIdRoute
}

const ApiLogsRouteChildren: ApiLogsRouteChildren = {
  ApiLogsLogIdRoute: ApiLogsLogIdRoute,
}

const ApiLogsRouteWithChildren =
  ApiLogsRoute._addFileChildren(ApiLogsRouteChildren)

interface ApiOrdersRouteChildren {
  ApiOrdersOrderIdRoute: typeof ApiOrdersOrderIdRoute
}

const ApiOrdersRouteChildren: ApiOrdersRouteChildren = {
  ApiOrdersOrderIdRoute: ApiOrdersOrderIdRoute,
}

const ApiOrdersRouteWithChildren = ApiOrdersRoute._addFileChildren(
  ApiOrdersRouteChildren,
)

interface ApiPostsRouteChildren {
  ApiPostsSlugRoute: typeof ApiPostsSlugRoute
}

const ApiPostsRouteChildren: ApiPostsRouteChildren = {
  ApiPostsSlugRoute: ApiPostsSlugRoute,
}

const ApiPostsRouteWithChildren = ApiPostsRoute._addFileChildren(
  ApiPostsRouteChildren,
)

interface ApiProductProductIdRouteChildren {
  ApiProductProductIdVariantRoute: typeof ApiProductProductIdVariantRoute
}

const ApiProductProductIdRouteChildren: ApiProductProductIdRouteChildren = {
  ApiProductProductIdVariantRoute: ApiProductProductIdVariantRoute,
}

const ApiProductProductIdRouteWithChildren =
  ApiProductProductIdRoute._addFileChildren(ApiProductProductIdRouteChildren)

interface ApiProductRouteChildren {
  ApiProductProductIdRoute: typeof ApiProductProductIdRouteWithChildren
}

const ApiProductRouteChildren: ApiProductRouteChildren = {
  ApiProductProductIdRoute: ApiProductProductIdRouteWithChildren,
}

const ApiProductRouteWithChildren = ApiProductRoute._addFileChildren(
  ApiProductRouteChildren,
)

interface ApiProductsRouteChildren {
  ApiProductsProductIdRoute: typeof ApiProductsProductIdRoute
}

const ApiProductsRouteChildren: ApiProductsRouteChildren = {
  ApiProductsProductIdRoute: ApiProductsProductIdRoute,
}

const ApiProductsRouteWithChildren = ApiProductsRoute._addFileChildren(
  ApiProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddInventoryRoute: AddInventoryRoute,
  AddOrderRoute: AddOrderRoute,
  AddProductRoute: AddProductRoute,
  ApiDocsRoute: ApiDocsRoute,
  BaiVietRoute: BaiVietRouteWithChildren,
  DangKyRoute: DangKyRoute,
  DangNhapRoute: DangNhapRoute,
  DanhSachSanPhamRoute: DanhSachSanPhamRoute,
  DashboardRoute: DashboardRoute,
  GioHangRoute: GioHangRoute,
  GioiThieuRoute: GioiThieuRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  NotFoundRoute: NotFoundRoute,
  OrdersRoute: OrdersRoute,
  ProductsRoute: ProductsRoute,
  QuenMatKhauRoute: QuenMatKhauRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SanPhamRoute: SanPhamRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminAddProductRoute: AdminAddProductRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminInventoryRoute: AdminInventoryRouteWithChildren,
  AdminLogsRoute: AdminLogsRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  ApiAddProductRoute: ApiAddProductRoute,
  ApiCategoriesRoute: ApiCategoriesRouteWithChildren,
  ApiGetBookmarkRoute: ApiGetBookmarkRoute,
  ApiLogsRoute: ApiLogsRouteWithChildren,
  ApiOrdersRoute: ApiOrdersRouteWithChildren,
  ApiPostsRoute: ApiPostsRouteWithChildren,
  ApiProductRoute: ApiProductRouteWithChildren,
  ApiProductsRoute: ApiProductsRouteWithChildren,
  ApiSendCartOrderRoute: ApiSendCartOrderRoute,
  ApiSendNewletterRoute: ApiSendNewletterRoute,
  ApiSendNewsletterRoute: ApiSendNewsletterRoute,
  ApiSendProductOrderRoute: ApiSendProductOrderRoute,
  EditProductProductIdRoute: EditProductProductIdRoute,
  ViewProductProductIdRoute: ViewProductProductIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEditProductProductIdRoute: AdminEditProductProductIdRoute,
  AdminViewProductProductIdRoute: AdminViewProductProductIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiEditProductProductIdRoute: ApiEditProductProductIdRoute,
  ApiProductImagesKeyRoute: ApiProductImagesKeyRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiUploadsProductImagesRoute: ApiUploadsProductImagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
