import { defaultHomeBlocks } from "../../cms/src/landing";

const target = new URL("../seeds/home.sql", import.meta.url);
const blocks = JSON.stringify(defaultHomeBlocks).replaceAll("'", "''");

const sql = `-- Generated by packages/db/scripts/generate-home-seed.ts.
-- The seed is non-destructive: it creates a new homepage, or upgrades only
-- a recognizable Hero-only fixture whose working copy still matches public.
-- The existing Hero is preserved; customer drafts and history always win.
BEGIN TRANSACTION;

INSERT OR IGNORE INTO pages (
  id,
  slug,
  title,
  template,
  blocks,
  status,
  seo_title,
  seo_description,
  version,
  updated_by,
  created_at,
  updated_at
) VALUES (
  'seed-page-home',
  'home',
  'Trang chủ',
  'landing',
  '${blocks}',
  'published',
  'Rèm Vina — Lưới chống muỗi may đo',
  'Lưới chống muỗi cao cấp may đo theo từng khung cửa, giữ nhà thoáng sáng và bảo vệ gia đình.',
  1,
  'seed',
  cast(unixepoch('subsecond') * 1000 as integer),
  cast(unixepoch('subsecond') * 1000 as integer)
);

INSERT OR IGNORE INTO page_revisions (
  id,
  page_id,
  version,
  snapshot,
  note,
  created_by,
  created_at
)
SELECT
  'seed-revision-page-home',
  id,
  version,
  json_object(
    'title', title,
    'slug', slug,
    'template', template,
    'blocks', json(blocks),
    'seoTitle', seo_title,
    'seoDescription', seo_description,
    'canonicalUrl', canonical_url,
    'ogImage', og_image,
    'robotsIndex', json(CASE WHEN robots_index = 1 THEN 'true' ELSE 'false' END),
    'robotsFollow', json(CASE WHEN robots_follow = 1 THEN 'true' ELSE 'false' END)
  ),
  'Initial published homepage seed',
  'seed',
  updated_at
FROM pages
WHERE id = 'seed-page-home' AND published_revision_id IS NULL;

UPDATE pages
SET
  published_revision_id = 'seed-revision-page-home',
  published_at = COALESCE(published_at, updated_at),
  updated_by = CASE WHEN updated_by = '' THEN 'seed' ELSE updated_by END
WHERE id = 'seed-page-home' AND published_revision_id IS NULL;

-- Upgrade a legacy Hero-only fixture only when working and public are still
-- identical. This also repairs environments where a test restored the legacy
-- revision after the first seed upgrade. The old revision remains immutable.
INSERT OR IGNORE INTO page_revisions (
  id,
  page_id,
  version,
  snapshot,
  note,
  created_by,
  created_at
)
SELECT
  'seed-revision-page-home-v' || (version + 1),
  id,
  version + 1,
  json_object(
    'title', title,
    'slug', slug,
    'template', template,
    'blocks', json(json_set(json('${blocks}'), '$[0]', json(json_extract(blocks, '$[0]')))),
    'seoTitle', seo_title,
    'seoDescription', seo_description,
    'canonicalUrl', canonical_url,
    'ogImage', og_image,
    'robotsIndex', json(CASE WHEN robots_index = 1 THEN 'true' ELSE 'false' END),
    'robotsFollow', json(CASE WHEN robots_follow = 1 THEN 'true' ELSE 'false' END)
  ),
  'Expand flagship homepage to the ten typed CMS blocks',
  'seed',
  cast(unixepoch('subsecond') * 1000 as integer)
FROM pages
WHERE
  id = 'seed-page-home'
  AND published_revision_id IS NOT NULL
  AND json_array_length(blocks) = 1
  AND json_extract(blocks, '$[0].type') = 'hero'
  AND EXISTS (
    SELECT 1
    FROM page_revisions AS published
    WHERE
      published.id = pages.published_revision_id
      AND json(json_extract(published.snapshot, '$.blocks')) = json(pages.blocks)
  );

INSERT OR IGNORE INTO audit_events (
  id,
  actor_user_id,
  actor_email,
  actor_role,
  action,
  entity_type,
  entity_id,
  before,
  after,
  request_id,
  created_at
)
SELECT
  'seed-audit-page-home-v' || (version + 1),
  'seed',
  '',
  'system',
  'page.seed_upgrade',
  'page',
  id,
  json_object('version', version, 'publishedRevisionId', published_revision_id),
  json_object(
    'version', version + 1,
    'publishedRevisionId', 'seed-revision-page-home-v' || (version + 1)
  ),
  'seed-home-v' || (version + 1),
  cast(unixepoch('subsecond') * 1000 as integer)
FROM pages
WHERE
  id = 'seed-page-home'
  AND published_revision_id IS NOT NULL
  AND json_array_length(blocks) = 1
  AND json_extract(blocks, '$[0].type') = 'hero'
  AND EXISTS (
    SELECT 1
    FROM page_revisions AS published
    WHERE
      published.id = pages.published_revision_id
      AND json(json_extract(published.snapshot, '$.blocks')) = json(pages.blocks)
  );

UPDATE pages
SET
  blocks = json_set(json('${blocks}'), '$[0]', json(json_extract(blocks, '$[0]'))),
  published_revision_id = 'seed-revision-page-home-v' || (version + 1),
  version = version + 1,
  published_at = cast(unixepoch('subsecond') * 1000 as integer),
  updated_by = 'seed',
  updated_at = cast(unixepoch('subsecond') * 1000 as integer)
WHERE
  id = 'seed-page-home'
  AND published_revision_id IS NOT NULL
  AND json_array_length(blocks) = 1
  AND json_extract(blocks, '$[0].type') = 'hero'
  AND EXISTS (
    SELECT 1
    FROM page_revisions AS published
    WHERE
      published.id = pages.published_revision_id
      AND json(json_extract(published.snapshot, '$.blocks')) = json(pages.blocks)
  );

COMMIT;
`;

await Bun.write(target, sql);
console.log(`Generated ${target.pathname}`);
